# Generated by Django 5.2.3 on 2025-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, upload_to='hero/'),
        ),
    ]
