# Generated by Django 5.2.3 on 2025-06-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hero_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
