# Generated by Django 5.2.3 on 2025-06-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hero_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HeroTypingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_texts', to='api.herosection')),
            ],
        ),
    ]
