# Generated by Django 5.2.3 on 2025-06-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_herosection_herotypingtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('facebook', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('messenger', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_images/')),
            ],
        ),
    ]
