# Generated by Django 5.2.3 on 2025-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herotypingtext',
            old_name='hero',
            new_name='hero_section',
        ),
        migrations.AlterField(
            model_name='herotypingtext',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
