# Generated by Django 5.2.3 on 2025-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_hero_herotypingtext_hero_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('web-design', 'Web Design'), ('web-development', 'Web Development'), ('ui-ux-design', 'UI/UX Design')], max_length=50)),
            ],
        ),
    ]
